format_version: 3
pipelines:
  build_formula_hellotap:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/c-n-c/homebrew_tapinstaller.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - build_stage:
        environment_variables:
          ARTIFACTORY: 10.1.5.86
          VERSION: ${GO_PIPELINE_COUNTER}
          COMMIT: ${GO_REVISION_GIT}
        secure_variables:
          GITUSR: AES:4dUpg629SixrCLTGt5uOPw==:3KlNE8Iva0VUdj/qc/15HA==
          GITPWD: AES:CybIMbbiqzaYgu3g892Y1w==:ZO3nQzwAdC/2KKwPnGZC6g==
          ARTUSR: AES:ZAo4Jxsla3LJkrn8OV/VwQ==:pW8z9nvc47a+zDlAmQ405w==
          ARTPWD: AES:+WFVIh/1DerDjHBtipkxUQ==:D3N27bsmfPrBQ2zal/vvYA==
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build_job:
            timeout: 0
            elastic_profile_id: demo-app
            artifacts:
            - build:
                source: hellotap/hellotap.rb
                destination: hellotap
            - build:
                source: hellotap/hellotap-test.rb
                destination: hellotap
            - build:
                source: hellotap/hellotap.zip
                destination: hellotap
            - build:
                source: hellotap/makefile
                destination: hellotap
            tasks:
            - exec:
                working_directory: hellotap
                command: make
                arguments:
                - "zip"
            - exec:
                working_directory: hellotap
                command: make
                arguments:
                - upload_zip
                - artfolder=generic-local
            - exec:
                working_directory: hellotap
                command: make
                arguments:
                - "generate_formula"
    - test_stage:
        environment_variables:
          ARTIFACTORY: 10.1.5.86
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test_job:
            resources:
            - "mac"
            timeout: 0
            tasks:
            - fetch:
                stage: build_stage
                job: build_job
                source: hellotap
            - exec:
                command: bash
                arguments:
                - -c
                - "if [ -f /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hellotap.rb ]; then \
                rm -rf /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hellotap.rb; \
                fi; \
                brew info hellotap; \
                if [ `echo $?` != 0 ]; then \
                brew uninstall hellotap; fi "
            - exec:
                command: cp
                arguments:
                - "hellotap/hellotap-test.rb"
                - "/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hellotap.rb"
            - exec:
                command: brew
                arguments:
                - install
                - --build-from-source
                - /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hellotap.rb
            - exec:
                command: brew
                arguments:
                - test
                - /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/hellotap.rb
    - publish_stage:
        environment_variables:
          ARTIFACTORY: 10.1.5.86
          VERSION: ${GO_PIPELINE_COUNTER}
          COMMIT: ${GO_REVISION_GIT}
        secure_variables:
          ARTUSR: AES:ZAo4Jxsla3LJkrn8OV/VwQ==:pW8z9nvc47a+zDlAmQ405w==
          ARTPWD: AES:+WFVIh/1DerDjHBtipkxUQ==:D3N27bsmfPrBQ2zal/vvYA==
          GITUSR: AES:4dUpg629SixrCLTGt5uOPw==:3KlNE8Iva0VUdj/qc/15HA==
          GITPWD: AES:CybIMbbiqzaYgu3g892Y1w==:ZO3nQzwAdC/2KKwPnGZC6g==
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          publish_job:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - fetch:
                stage: build_stage
                job: build_job
                source: hellotap
            - exec:
                working_directory: hellotap
                command: make
                arguments:
                - "upload_zip"
                - artfolder=release-local
            - exec:
                working_directory: hellotap
                command: make
                arguments:
                - "upload_formula"