format_version: 3
pipelines:
  build_formula_hellotap:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/c-n-c/homebrew_tapinstaller.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - default_stage:
        environment_variables:
          ARTIFACTORY: 10.1.5.86
        secure_variables:
          GITUSR: AES:dIDN8kdiLxuALkQ2MgWOKA==:O62AFR1UwywMiuHAKg/1sQ==
          GITPWD: AES:+g2LqXJjPTwfjREfMslbXA==:CDN1Wvm86NkJ4v4YPvEYeg==
          ARTUSR: AES:TyrVNjq/SZThbdiAT8Oz9w==:EysYozK/jYasJv6pXD3riA==
          ARTPWD: AES:5Uk4sdauRLNPomgaJoT9oA==:Htls5EY5Np0TQat9cPMRGA==
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          default_job:
            timeout: 0
            elastic_profile_id: demo-app
            tasks:
            - exec:
                working_directory: hellotap
                command: ls
                arguments:
                - "-ltra"
            - exec:
                working_directory: hellotap
                command: make
                arguments:
                - "zip"


