format_version: 3
pipelines:
  build_formula_hellotap:
    group: sample
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/c-n-c/homebrew_tapinstaller.git
        shallow_clone: true
        auto_update: true
        branch: master
    stages:
    - default_stage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          default_job:
            timeout: 0
            tabs:
              Sample: my-artifact.html
            elastic_profile_id: demo-app
            tasks:
            - exec:
                command: pwd
            - exec:
                command: which make
            - exec:
                command: make zip

